ALTER TABLE users 
ADD COLUMN address_country VARCHAR(100) NULL,
ADD COLUMN address_city VARCHAR(100) NULL,
ADD COLUMN address_apartment VARCHAR(100) NULL,
ADD COLUMN address_postal_code VARCHAR(50) NULL;

CREATE TABLE IF NOT EXISTS user_payment_methods (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    card_number_masked VARCHAR(20) NULL,
    card_expiry VARCHAR(10) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_payment_methods_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
